local   all             postgres                                trust
host    all             postgres        127.0.0.1/32            trust
local   all             foodmart                                trust
host    all             foodmart        127.0.0.1/32            trust
