
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Sep 30 11:47:39 EDT 2016
//----------------------------------------------------

package mondrian.olap;

/** CUP generated interface containing symbol constants. */
public interface ParserSym {
  /* terminals */
  public static final int PLAN = 30;
  public static final int CAST = 6;
  public static final int WHEN = 38;
  public static final int WITH = 41;
  public static final int GE = 50;
  public static final int CONCAT = 47;
  public static final int ASTERISK = 43;
  public static final int EMPTY = 13;
  public static final int DIMENSION = 10;
  public static final int _VALUE_EXPRESSION = 42;
  public static final int XOR = 40;
  public static final int CASE = 5;
  public static final int PAGES = 29;
  public static final int LPAREN = 54;
  public static final int QUOTED_ID = 64;
  public static final int MINUS = 56;
  public static final int FOR = 17;
  public static final int ROWS = 33;
  public static final int WHERE = 39;
  public static final int RPAREN = 60;
  public static final int NOT = 25;
  public static final int IS = 20;
  public static final int AND = 2;
  public static final int LT = 55;
  public static final int IN = 19;
  public static final int OR = 28;
  public static final int COMMA = 46;
  public static final int BANG = 44;
  public static final int NON = 24;
  public static final int ON = 27;
  public static final int SELECT = 35;
  public static final int PLUS = 58;
  public static final int FORMULA_STRING = 67;
  public static final int MEMBER = 23;
  public static final int ID = 63;
  public static final int DOT = 48;
  public static final int LE = 53;
  public static final int EOF = 0;
  public static final int RETURN = 32;
  public static final int MATCHES = 21;
  public static final int DRILLTHROUGH = 11;
  public static final int error = 1;
  public static final int NULL = 26;
  public static final int NUMBER = 62;
  public static final int UNKNOWN = 68;
  public static final int EQ = 49;
  public static final int FROM = 18;
  public static final int SOLIDUS = 61;
  public static final int COLON = 45;
  public static final int LBRACE = 52;
  public static final int ELSE = 12;
  public static final int EXPLAIN = 15;
  public static final int PROPERTIES = 31;
  public static final int SECTIONS = 34;
  public static final int FIRSTROWSET = 16;
  public static final int COLUMNS = 9;
  public static final int AXIS = 4;
  public static final int RBRACE = 59;
  public static final int THEN = 37;
  public static final int NE = 57;
  public static final int END = 14;
  public static final int STRING = 66;
  public static final int MAXROWS = 22;
  public static final int AMP_QUOTED_ID = 65;
  public static final int CELL = 7;
  public static final int AS = 3;
  public static final int GT = 51;
  public static final int CHAPTERS = 8;
  public static final int SET = 36;
}

