<?xml version="1.0"?> 
<!--
  == $Id$
  == This software is subject to the terms of the Common Public License
  == Agreement, available at the following URL:
  == http://www.opensource.org/licenses/cpl.html.
  == Copyright (C) 2007-2007 Julian Hyde and others.
  == All Rights Reserved.
  == You must accept the terms of that agreement to use this software.
  -->
<!-- This stylesheet takes as input a DiffRepository .ref.xml file -->
<!-- containing Foodmart query/result pairs -->
<!-- and generates a JUnit class for running them from within an IDE. -->
<xsl:stylesheet 
  version="1.0" 
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
  >
  <xsl:output method="text" indent="no" />

  <xsl:param name="reffile"/>
  <xsl:param name="packagename"/>
  <xsl:param name="classname"/>

  <xsl:template match="Root">
// DO NOT EDIT THIS FILE OR CHECK IT INTO PERFORCE!
// This class was generated by ant target generateDiffRepositoryJUnit
// from <xsl:value-of select="$reffile"/>
package <xsl:value-of select="$packagename"/>;

/**
 * Wraps DiffRepository-based tests with JUnit test methods so
 * that you can see the query and result directly from within your 
 * favorite JUnit-aware IDE.
 */
public class <xsl:value-of select="$classname"/> extends FoodMartTestCase
{
  
    public <xsl:value-of select="$classname"/>(String testName)
        throws Exception
    {
        super(testName);
    }
    <xsl:apply-templates select="node()" />
}
  </xsl:template>

  <xsl:template name="genTxt">
    <xsl:param name="text" select="."/>
    <xsl:param name="start" select="substring(normalize-space($text),1,1)"/>
    <xsl:param name="ltrim" 
      select="concat($start,substring-after($text,$start))"/>
    <xsl:call-template name="breakLines">
      <xsl:with-param name="text" select="$ltrim"/>
    </xsl:call-template>
  </xsl:template>

  <xsl:template name="breakLines">
    <xsl:param name="text" select="."/>
    <xsl:choose>
      <xsl:when test="normalize-space($text)=''">
      </xsl:when>
      <xsl:when test="contains($text, '&#xa;')">
        <xsl:value-of select="substring-before($text, '&#xa;')"/>
        <xsl:value-of select="'\n&quot; +&#xa;&quot;'"/>
        <xsl:call-template name="breakLines">
          <xsl:with-param name="text" select="substring-after($text,
            '&#xa;')"/>
        </xsl:call-template>
      </xsl:when>
      <xsl:otherwise>
	<xsl:value-of select="$text"/>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

  <xsl:template match="TestCase">
    public void <xsl:value-of select="@name"/>()
        throws Exception
    {
        assertQueryReturns(
&quot;<xsl:call-template name="genTxt">
      <xsl:with-param name="text" select="Resource[@name='mdx']"/>
      </xsl:call-template>&quot;, 
            fold(
&quot;<xsl:call-template name="genTxt">
      <xsl:with-param name="text" select="Resource[@name='result']"/>
      </xsl:call-template>&quot;));
    }
  </xsl:template>

}
</xsl:stylesheet>
